export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  author: string;
  date: string;
  readMinutes: number;
  body: string[];
};

export const posts: Post[] = [
  {
    slug: "istanbul-bosanma-davasi-rehberi",
    title: "İstanbul'da Boşanma Davası: Yetkili Aile Mahkemesi, Süreç ve Avukat Rehberi",
    excerpt:
      "İstanbul Avrupa ve Anadolu Yakası Aile Mahkemelerinde boşanma davası açarken yetki kuralları, anlaşmalı ve çekişmeli süreçler, nafaka, velayet, mal rejimi ve ortalama süreler üzerine pratik bir İstanbul boşanma avukatı rehberi.",
    category: "Aile Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-12",
    readMinutes: 10,
    body: [
      "Boşanma davası, evliliğin hâkim kararıyla sona erdirildiği ve Türk Medeni Kanunu çerçevesinde düzenlenen bir yargılama sürecidir. İstanbul'da boşanma davaları, eşlerden birinin yerleşim yerinin bulunduğu yerdeki Aile Mahkemesinde açılır.",
      "İstanbul, yargı teşkilatı bakımından Avrupa Yakası ve Anadolu Yakası olmak üzere ikiye ayrılmıştır. Beşiktaş, Şişli, Kâğıthane ve Eyüpsultan gibi ilçelerde yerleşim yeri bulunan eşler için İstanbul Aile Mahkemeleri; Kadıköy, Maltepe, Üsküdar gibi ilçelerde yerleşim yeri bulunanlar için Anadolu Aile Mahkemeleri yetkilidir.",
      "Anlaşmalı boşanmanın hukuki temeli Türk Medeni Kanunu'nun 166/3. maddesidir. Evliliğin en az bir yıl sürmüş olması, eşlerin mahkemeye birlikte başvurması ya da birinin diğerinin açtığı davayı kabul etmesi ve hâkim huzurunda iradelerini bizzat açıklamaları gerekir. Eksiksiz hazırlanmış bir protokolle desteklenen başvurular İstanbul Aile Mahkemelerinde çoğunlukla 4-8 hafta içinde tek celse ile sonuçlanır.",
      "Çekişmeli boşanma süreçlerinde mahkeme; tanık beyanlarını, mesajlaşma kayıtlarını, sosyal medya verilerini, banka hareketlerini ve gerektiğinde uzman raporlarını birlikte değerlendirir. Hukuka aykırı yollarla elde edilmiş delillerin yargılamada kabul görmediği unutulmamalıdır.",
      "Velayet talebinde mahkeme öncelikle çocuğun üstün yararını esas alır. Yaş, eğitim ihtiyacı, anne-baba ile kurulan duygusal bağ ve pedagog raporları belirleyici unsurlardır. Velayet kesinleşinceye kadar geçici velayet ve kişisel ilişki tedbirleri talep edilebilir.",
      "Tedbir nafakası, dava süresince eşin ve çocukların geçimini sağlamak amacıyla bağlanır. Karar kesinleştikten sonra ise iştirak nafakası çocuklar için, yoksulluk nafakası ise kusursuz veya az kusurlu eş için ödenebilir. Yoksulluk nafakası süresiz olabilmektedir.",
      "Maddi tazminat, boşanma nedeniyle mevcut veya beklenen menfaatleri zedelenen kusursuz veya daha az kusurlu eşe ödenir. Manevi tazminat ise kişilik haklarının saldırıya uğraması durumunda gündeme gelir; özellikle aldatma ve fiziksel şiddet gibi sebeplerde talep edilir.",
      "Edinilmiş mallara katılma rejimi 2002 sonrası evliliklerde yasal rejimdir. Boşanmayla birlikte tasfiyeye girer; katılma alacağı ve değer artış payı talepleri ayrı bir mal rejimi davasında ele alınır. İstanbul gibi gayrimenkul ve şirket varlıklarının yoğun olduğu bir şehirde mal rejimi tasfiyesi titiz bir bilirkişi incelemesi gerektirir.",
      "İstanbul Aile Mahkemelerinde çekişmeli boşanma davaları; delil toplama, tanık dinleme, bilirkişi raporu ve istinaf süreçleri nedeniyle ortalama 14-26 ay sürebilmektedir. Yurt dışı boyutlu ve yüksek değerli mal rejimi içeren dosyalarda bu süre daha da uzayabilir.",
      "Stratejik hatalar bakımından en sık karşılaşılanlar; sosyal medyada karşı tarafa zarar verecek paylaşımlar yapmak, hukuka aykırı delil sunmak, gereksiz tanık listesi vermek ve müzakere zeminini erkenden kaybetmektir.",
      "İstanbul'da çekişmeli sürecin orta vadede anlaşmalıya dönüştürülmesi yargılama açısından lehe sonuçlar üretebilir. İyi hazırlanmış bir protokol taslağı, sürecin her aşamasında uzlaşma kapısını açık tutar.",
      "KARDAK Hukuk Bürosu'nun Beşiktaş ofisi olarak İstanbul Avrupa ve Anadolu Yakası Aile Mahkemelerinde boşanma davalarını; delil disiplini, müvekkil iletişimi ve mümkün olduğunda uzlaşma odaklı stratejilerle yönetiyoruz. Ankara Bilkent ofisimizle birlikte iki şehri kapsayan tek hat dosya yönetimi sağlıyoruz.",
    ],
  },
  {
    slug: "istanbul-ceza-avukati-rehberi",
    title: "İstanbul Ceza Avukatı: Soruşturma ve Kovuşturma Aşamasında Hak Arayışı",
    excerpt:
      "İstanbul'da şüpheli ya da sanık sıfatıyla yer alınan ceza dosyalarında ifade, tutuklama, adli kontrol, kovuşturma, istinaf ve infaz aşamalarında bir İstanbul ceza avukatının rolü ve kritik hakların pratik anlatımı.",
    category: "Ceza Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-11",
    readMinutes: 9,
    body: [
      "Ceza yargılaması; şüpheli, sanık veya mağdur sıfatıyla yer alınan en hassas hukuki süreçlerden biridir. İstanbul'da ceza dosyaları soruşturma aşamasında İstanbul Cumhuriyet Başsavcılığı (Çağlayan Adliyesi) ile Anadolu Cumhuriyet Başsavcılığı tarafından, kovuşturma aşamasında ise İstanbul ve Anadolu Asliye veya Ağır Ceza Mahkemelerinde yürütülür.",
      "Soruşturma aşamasında ilk işlem genellikle ifade alınmasıdır. Şüphelinin susma hakkı, avukat bulundurma hakkı ve aleyhine delil göstermeme hakkı temel anayasal güvencelerdir. İstanbul'da kollukta veya savcılıkta ifade verilirken bu hakların hatırlatılması zorunludur; aksi hâlde alınan ifade hukuka aykırı kabul edilebilir.",
      "İfade aşamasında avukat eşliğinde olmamak çoğu zaman ileride telafisi güç hatalara yol açar. Teknik suç tipleri ve hukuki nitelendirmeler konusunda hukukçu olmayan birinin doğru beyanda bulunması beklenemez. Bu nedenle ilk anlardan itibaren bir İstanbul ceza avukatıyla görüşmek önerilir.",
      "Tutuklama, Anayasa'nın 19. maddesi ve Ceza Muhakemesi Kanunu çerçevesinde ancak somut delillere ve kuvvetli suç şüphesine dayalı olarak verilebilen istisnai bir koruma tedbiridir. İstanbul Sulh Ceza Hakimliklerinin tutuklama kararlarına karşı yedi gün içinde itiraz edilebilir.",
      "Adli kontrol, tutuklama yerine başvurulan ve yurt dışına çıkış yasağı, imza atma yükümlülüğü, ev hapsi gibi tedbirleri içerebilen bir kurumdur. İstanbul uygulamasında giderek artan biçimde adli kontrol tercih edilmektedir; ihlal hâlinde doğrudan tutuklamaya çevrilebilir.",
      "Kovuşturma aşamasında iddianamenin kabulüyle birlikte dosya İstanbul Asliye veya Ağır Ceza Mahkemesine devredilir. Hangi mahkemenin görevli olduğu, suça öngörülen ceza miktarına göre belirlenir. Ağırlaştırılmış müebbet, müebbet ve on yıldan fazla hapis cezalı suçlar Ağır Ceza Mahkemesinin görev alanındadır.",
      "Kovuşturma boyunca tanıkların dinlenmesi, sanığın savunma yapması, bilirkişi raporlarının değerlendirilmesi ve esas hakkındaki mütalaa süreçleri yer alır. Avukat; her aşamada delillere itiraz etme, ek delil sunma ve süre uzatma talep etme hakkını kullanır.",
      "Mağdur ve katılan vekilliği de ceza avukatlığının önemli bir parçasıdır. Mağdurun zararlarının tespit edilmesi, suçtan zarar gören sıfatıyla davaya katılma talebi ve maddi-manevi tazminat hakları stratejik biçimde takip edilir.",
      "Karar verildikten sonra istinaf yolu açıktır. İstanbul Bölge Adliye Mahkemesi Ceza Daireleri istinaf incelemesi yapar; istinaf kararına karşı bazı dosyalarda Yargıtay'a temyiz yolu açıktır. Bu aşamalarda sürelerin titiz takibi büyük önem taşır.",
      "İnfaz süreci ise kararın kesinleşmesinden sonra başlar. Denetimli serbestlik, koşullu salıverilme, açık ceza infaz kurumuna ayrılma gibi pek çok kurum infaz hukukunun kapsamındadır. Hatalı infaz hesapları için İstanbul İnfaz Hakimliklerine itiraz yolu açıktır.",
      "Beşiktaş ofisimiz İstanbul Avrupa Yakası adliyelerine yakınlığıyla ifade ve duruşma takibinde hız sağlamaktadır. Anadolu Yakası dosyalarında Kartal Adliyesi süreçleri de aynı ekip tarafından yönetilmektedir.",
      "KARDAK Hukuk Bürosu olarak İstanbul'da ceza dosyalarını; soruşturmanın ilk dakikasından infaza kadar her aşamada müvekkilin haklarını korumak temel anlayışıyla yürütüyor, ölçülü ve delile dayalı bir savunma diliyle çalışıyoruz.",
    ],
  },
  {
    slug: "istanbul-miras-davasi-veraset",
    title: "İstanbul'da Miras Davası ve Veraset İlamı: Sulh Hukuk Mahkemesinde Adım Adım Süreç",
    excerpt:
      "İstanbul Sulh Hukuk Mahkemelerinde veraset ilamı, mirasın reddi, tenkis davası, muris muvazaası ve ortaklığın giderilmesi süreçlerini Avrupa ve Anadolu Yakası uygulaması üzerinden anlatan bir İstanbul miras avukatı rehberi.",
    category: "Miras Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-09",
    readMinutes: 9,
    body: [
      "Miras hukuku uyuşmazlıkları, mirasçılar arasında çoğu zaman duygusal ve mali gerginlikleri bir arada barındırır. İstanbul'da miras davaları büyük ölçüde İstanbul ve Anadolu Sulh Hukuk Mahkemelerinin görev alanındadır.",
      "Veraset ilamı çıkartmak miras süreçlerinin ilk adımıdır. İstanbul'da veraset ilamı için Sulh Hukuk Mahkemelerine başvurulabileceği gibi, mirasçılar arasında uyuşmazlık yoksa noterler aracılığıyla da çıkartılabilmektedir. Yabancı uyruklu mirasçı bulunan dosyalarda yetki yalnızca mahkemelerdedir.",
      "Mirasın reddi başvurusunda süre üç aydır. Bu süre, mirasçının murisin ölümünü öğrendiği tarihten itibaren işlemeye başlar. İstanbul Sulh Hukuk Mahkemesine yapılan başvuru sözlü veya yazılı olabilir. Sürenin geçirilmesi hâlinde miras kayıtsız şartsız kabul edilmiş sayılır.",
      "Terekenin tespiti, mirasın açıldığı an itibarıyla mal varlığının yargı önünde belgelenmesini sağlar. İstanbul gibi taşınmaz, banka ve şirket varlıklarının yoğun olduğu bir şehirde tereke tespiti ileride açılacak ortaklığın giderilmesi davaları için kritik bir delil zemini oluşturur.",
      "Tenkis davası, saklı paylı mirasçıların saklı paylarını ihlal eden bağışlamalar veya vasiyet hükümleri için açılır. Davanın açılabilmesi için saklı pay sahibinin saklı payına yapılan tecavüzü ve ölümü öğrenmesinden itibaren bir yıl, her hâlde mirasın açılmasından itibaren on yıllık süre içinde dava açılması gerekir.",
      "Muris muvazaası davası, murisin sağlığında saklı pay sahibi mirasçısını mirastan kaçırmak amacıyla taşınmazı görünüşte sattığı iddiasıyla gündeme gelir. İstanbul'da yüksek değerli gayrimenkul devirlerinde sık karşılaşılan bu davalarda zamanaşımı yoktur ancak ispat yükü davacıdadır.",
      "Ortaklığın giderilmesi (izale-i şuyu) davası, taşınmaz ve menkul mallarda ortak mülkiyetin sona erdirilmesi için açılır. İstanbul'da Sulh Hukuk Mahkemelerinin görev alanındaki bu davalarda mahkeme; taşınmaz aynen taksim edilebiliyorsa aynen, edilemiyorsa satış suretiyle ortaklığı giderir.",
      "Vasiyetname düzenlemesi miras süreçlerinin önceden planlanmasında en etkili araçlardan biridir. Resmi vasiyetname noter huzurunda, el yazılı vasiyetname tarih ve imzayla murisin kendi el yazısıyla, sözlü vasiyet ise yalnızca olağanüstü koşullarda düzenlenebilir.",
      "Mirastan feragat sözleşmesi, muris sağlığında bir mirasçının ileride doğacak miras hakkından feragat etmesini sağlar. Bu sözleşme noter huzurunda resmi şekilde yapılmadığı sürece geçerli değildir; karşılıklı veya tek taraflı olabilir.",
      "İstanbul Sulh Hukuk Mahkemelerinde miras davalarının ortalama süresi; uyuşmazlığın niteliğine göre 10-20 ay arasında değişebilmektedir. Bilirkişi gerektiren karmaşık tereke incelemelerinde süre daha da uzayabilir.",
      "Pratik bir öneri olarak; mirasçılar muris öldükten sonra hızlıca veraset ilamı çıkarmalı, banka ve tapu kayıtlarını dondurmak için tedbir talep etmeli ve tereke borcu varsa mirasın reddi süresini kaçırmamalıdır. İstanbul gibi yüksek değerli mal varlığına sahip dosyalarda profesyonel destek almak süreci kısaltır.",
      "KARDAK Hukuk Bürosu'nun Beşiktaş ofisi olarak İstanbul'da miras davalarını Ankara Bilkent ofisimizle birlikte tek hat üzerinden yönetiyor; tereke tespiti, mirasın reddi, tenkis, muvazaa ve ortaklığın giderilmesi süreçlerinde mirasçıların menfaatlerini dengeli biçimde gözetiyoruz.",
    ],
  },
  {
    slug: "istanbul-is-mahkemesi-ise-iade",
    title: "İstanbul İş Mahkemesinde İşe İade Davası: Süreler, Arabuluculuk ve Karar Süreci",
    excerpt:
      "İstanbul'da haksız feshe maruz kalan işçinin işe iade davası açabilmesi için gerekli şartlar, arabuluculuk zorunluluğu, Avrupa-Anadolu Yakası iş mahkemeleri uygulaması ve işe başlatmama tazminatı.",
    category: "İş Hukuku",
    author: "Av. Berk Erdem Işık",
    date: "2026-05-05",
    readMinutes: 8,
    body: [
      "İşe iade davası, iş güvencesi kapsamında çalışan işçinin iş sözleşmesinin işveren tarafından geçerli bir sebebe dayanmadan feshedilmesi hâlinde başvurabileceği bir hukuki yoldur. İstanbul'da bu davalar Avrupa Yakası İş Mahkemeleri ile Anadolu İş Mahkemelerinin görev alanındadır.",
      "Davanın açılabilmesi için iş güvencesi şartlarının sağlanması gerekir. İşçinin çalıştığı işyerinde en az otuz işçinin bulunması, işçinin en az altı aylık kıdeminin olması ve iş sözleşmesinin işveren tarafından feshedilmiş olması temel şartlardır. İstanbul'da büyük ölçekli şirketlerin yoğun olması sebebiyle iş güvencesi kapsamına giren çalışan sayısı yüksektir.",
      "Fesih bildiriminin işçiye tebliğinden itibaren bir aylık süre içinde işçinin arabulucuya başvurması zorunludur. İstanbul Çalışma ve İş Kurumu İl Müdürlüğüne bağlı arabulucu listelerinden seçim yapılabileceği gibi taraflar ortak bir arabulucu üzerinde de anlaşabilir.",
      "Arabuluculuk görüşmelerinde anlaşma sağlanırsa süreç burada sona erer ve anlaşma tutanağı ilam niteliğinde icra kabiliyetine sahip olur. Anlaşma sağlanamazsa son tutanağın düzenlenmesinden itibaren iki hafta içinde İstanbul İş Mahkemesinde dava açılmalıdır.",
      "Hak düşürücü nitelikteki bu süreler kaçırıldığında dava esastan değil; süre yönünden reddedilir. Bu nedenle fesih bildirimi tebliğ alındığı anda takvim oluşturmak ve bir İstanbul iş avukatıyla görüşmek kritik önem taşır.",
      "Mahkeme, feshin geçerli sebebe dayanıp dayanmadığını araştırırken işyeri kayıtları, performans değerlendirme raporları, disiplin kurulu kararları, tanık beyanları ve gerektiğinde bilirkişi incelemesinden yararlanır. İstanbul İş Mahkemelerinin uygulamasında savunma alınmadan yapılan fesihler büyük ölçüde geçersiz kabul edilmektedir.",
      "İşe iade kararı kesinleştiğinde işçi, kararın kendisine tebliğinden itibaren on iş günü içinde işverene başvurarak işe başlamak istediğini bildirir. İşveren bu başvurudan itibaren bir ay içinde işçiyi işe başlatmakla yükümlüdür.",
      "İşveren işçiyi tekrar işe başlatmazsa, mahkemece belirlenen 4 ile 8 aylık ücret tutarındaki işe başlatmama tazminatı ile boşta geçen sürenin en çok dört aylık ücret tutarı işçiye ödenmek zorundadır. Bu hakların talep edilebilmesi için işçinin süresi içinde işverene başvurmuş olması şarttır.",
      "İşe iade davası ile birlikte ödenmemiş kıdem ve ihbar tazminatı, fazla mesai, hafta tatili ve genel tatil ücreti gibi işçilik alacakları ayrı bir davayla veya birleştirilerek talep edilebilir. İstanbul'da bu davalar çoğunlukla aynı iş mahkemesinde görülür.",
      "İşveren tarafının dikkat etmesi gereken nokta ise fesih sürecini yazılı belgelerle desteklemek, savunma almayı ihmal etmemek ve performans uyarılarını dosyaya işlemektir. İstanbul İş Mahkemelerinin yerleşik içtihatları savunma alınmamış fesihleri büyük ölçüde geçersiz kabul etmektedir.",
      "KARDAK Hukuk Bürosu'nun Beşiktaş ofisi olarak İstanbul İş Mahkemelerinde işe iade davalarını; sürelerin titiz takibi, delil hazırlığı ve müvekkilin işletmeyle ilişkisinin korunması ekseninde stratejik biçimde yönetiyoruz.",
    ],
  },
  {
    slug: "istanbul-gayrimenkul-tapu-iptal",
    title: "İstanbul'da Tapu İptal ve Tescil Davası: Gayrimenkul Uyuşmazlıklarında Yol Haritası",
    excerpt:
      "İstanbul'da tapu iptal ve tescil davası açılırken yetkili Asliye Hukuk Mahkemesi, muris muvazaası, hile, ehliyetsizlik, kat mülkiyeti ve imar uyuşmazlıkları üzerine kapsamlı bir İstanbul gayrimenkul avukatı rehberi.",
    category: "Gayrimenkul Hukuku",
    author: "Av. Servet Ağcakaya",
    date: "2026-05-03",
    readMinutes: 9,
    body: [
      "Tapu iptal ve tescil davası, Türk hukukunda gayrimenkul mülkiyetiyle ilgili uyuşmazlıkların en sık karşılaşılan dava türlerinden biridir. İstanbul'da bu davalar, taşınmazın bulunduğu yerdeki Asliye Hukuk Mahkemesinin görev alanındadır. Avrupa Yakası taşınmazları için İstanbul, Anadolu Yakası taşınmazları için Anadolu Asliye Hukuk Mahkemeleri yetkilidir.",
      "Davanın açılmasında en sık görülen sebepler; muris muvazaası, satış sözleşmesinin geçersizliği, hile, ehliyetsizlik, hukuken geçerli olmayan irade beyanı ve imar yolsuzluğudur. Her sebep farklı ispat unsurları gerektirir.",
      "Muris muvazaası davası, miras hukukuyla iç içe geçen ve İstanbul Asliye Hukuk Mahkemelerinde sık görülen bir dava türüdür. Özellikle yüksek değerli İstanbul taşınmazlarında, murisin sağlığında saklı pay sahibi mirasçısını mirastan kaçırmak amacıyla görünüşte sattığı kabul edilen işlemler bu davaya konu olmaktadır.",
      "Ehliyetsizlik nedeniyle açılan tapu iptal davalarında, taşınmazın devri sırasında devredenin akıl sağlığı yerinde olmaması veya işin niteliği ve sonuçlarını kavrayacak durumda olmaması gerekir. Mahkeme; sağlık kuruluşu raporları, tanık beyanları ve adli tıp incelemesiyle değerlendirme yapar.",
      "Hile sebebiyle açılan davalarda satıcının ya da alıcının diğer tarafı yanıltıcı beyanlarla iradeyi etkilediği kabul edilir. İspat yükü hile iddiasında bulunan tarafa aittir ve genellikle yazılı belgeler, mesaj kayıtları ve tanık beyanları üzerinden değerlendirme yapılır.",
      "Kira ilişkisinden doğan tahliye davaları gayrimenkul hukukunun bir başka yoğun alanıdır. İstanbul'da konut ve çatılı işyeri kiralarında tahliye davaları Sulh Hukuk Mahkemelerinin görev alanındadır; özel sebepler dışında en az on yıllık kira ilişkisinde özel ihbar yolu öngörülmüştür.",
      "Kat mülkiyeti uyuşmazlıkları apartman ve site yönetiminden doğan anlaşmazlıkları kapsar. Ortak gider alacakları, genel kurul kararlarının iptali, yönetici tayini ve ortak yer kullanımı süreçleri İstanbul Sulh Hukuk Mahkemelerinde sık karşılaşılan dava türlerindendir.",
      "Gayrimenkul alım-satım sözleşmelerinde tapu siciline güven ilkesi büyük önem taşır. Tapuya tescil edilmiş bir mülkiyet kaydına iyi niyetle güvenen üçüncü kişi, sonradan iptal davasıyla karşılaştığında kazanmış olduğu hakkı koruyabilir. Bu nedenle İstanbul gibi yoğun gayrimenkul piyasası olan bir şehirde alımdan önce tapu kayıt geçmişi titizlikle incelenmelidir.",
      "İmar uygulamalarından doğan ihtilaflar idari yargının görev alanındadır. İstanbul'da imar planı değişiklikleri, parselasyon işlemleri ve kamulaştırma kararlarına karşı İstanbul İdare Mahkemelerine başvurulur. Sürelerin titiz takibi şarttır; iptal davası süresi tebliğden itibaren altmış gündür.",
      "Pratik bir öneri olarak; İstanbul'da gayrimenkul almadan önce tapu sorgusu, imar durumu sorgulaması, varsa şerh ve haciz kayıtlarının incelenmesi, kat mülkiyeti durumunun değerlendirilmesi ve yapı kullanma izninin var olduğunun teyit edilmesi sonradan açılacak davaların büyük çoğunluğunu önler.",
      "Yargılama süreleri açısından, tapu iptal davaları İstanbul'da bilirkişi gerektirmesi nedeniyle ortalama 16-26 ay sürmektedir. İstinaf ve Yargıtay aşamalarıyla birlikte toplam süre üç yılı aşabilmektedir.",
      "KARDAK Hukuk Bürosu'nun Beşiktaş ofisi olarak İstanbul'da gayrimenkul davalarını; alım öncesi due diligence çalışmasından tapu iptal, tahliye, kat mülkiyeti ve imar süreçlerine kadar her aşamada müvekkillerimizle birlikte yürütüyoruz.",
    ],
  },
  {
    slug: "ankara-avukat-secimi-rehberi",
    title: "Ankara'da Avukat Seçimi: Doğru Hukuk Bürosunu Bulmak İçin 8 Kriter",
    excerpt:
      "Ankara'da bir hukuki süreçte yanınızda olacak avukatı seçerken bakmanız gereken sekiz temel kriter: uzmanlık, baro kaydı, iletişim ritmi, şeffaf ücretlendirme, yazılı sözleşme ve daha fazlası.",
    category: "Rehber",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-12",
    readMinutes: 8,
    body: [
      "Ankara'da bir hukuki süreç için avukat ararken çoğu zaman karşımıza onlarca büro, farklı uzmanlık iddiası ve birbirinden çok farklı ücretlendirme yaklaşımı çıkar. Doğru avukatı seçmek; sürecin sonucunu, harcanan zamanı ve duygusal yükü doğrudan etkiler.",
      "Birinci kriter: doğru uzmanlık alanı. Ankara'da pek çok avukat genel hukuk pratiği yapar ancak ceza, aile, ticaret veya idare gibi alanlarda derinleşmiş bir hukuk bürosunu tercih etmek davanızın seyrini belirleyebilir. Sözleşme öncesinde avukatın benzer dosyalardaki deneyimini sorgulamak yararlı olacaktır.",
      "İkinci kriter: baro kaydı ve disiplin geçmişi. Ankara Barosu'nun resmi sayfasından avukatın aktif olarak meslek icra ettiğini ve hakkında herhangi bir disiplin işlemi bulunmadığını doğrulayabilirsiniz. Bu basit kontrol, gelecekte yaşanabilecek pek çok sorunu en başta önler.",
      "Üçüncü kriter: iletişim ritmi. Avukatınızın mesajlarınıza ne kadar sürede döndüğü, dosyanız hakkında sizi nasıl bilgilendirdiği ve önemli aşamaları yazılı olarak paylaşıp paylaşmadığı süreçteki güveni belirler. İlk görüşmede iletişim şeklinin net biçimde konuşulması faydalıdır.",
      "Dördüncü kriter: şeffaf ücretlendirme. Türkiye Barolar Birliği'nin Avukatlık Asgari Ücret Tarifesi temel referanstır. İyi bir Ankara hukuk bürosu; ücret kalemlerini, ödeme takvimini, başarıya bağlı ek ödeme varsa hesaplama yöntemini yazılı avukatlık sözleşmesiyle baştan belirler.",
      "Beşinci kriter: yazılı avukatlık sözleşmesi. Sözlü anlaşmalar ileride yorum farkına yol açabilir. Sözleşmede vekaletin kapsamı, ücret ve masrafların paylaşımı, görev tanımı ve dosyanın sona erme koşulları açıkça yer almalıdır.",
      "Altıncı kriter: dosya yönetim disiplini. Ankara adliyelerinde tek bir avukatın yüzlerce dosyayı eş zamanlı yönetmeye çalıştığı durumlarda hatalar artmaktadır. Tercih ettiğiniz hukuk bürosunun dosya başına ayırdığı çalışma kapasitesini ve ekip yapısını sorgulamak önemlidir.",
      "Yedinci kriter: gizlilik ve veri güvenliği. Avukatlık Kanunu kapsamındaki sır saklama yükümlülüğüne ek olarak KVKK uyum süreçleri, dijital iletişim güvenliği ve dosya saklama disipliniyle ilgili sorular sormaktan çekinmeyin.",
      "Sekizinci kriter: ön görüşme niteliği. İyi bir Ankara avukatı, ilk görüşmede size pazarlama yapmak yerine; dosyanızın gerçek risklerini, alternatif çözüm yollarını, mahkeme süreçlerinin ortalama sürelerini ve maliyet aralığını net biçimde anlatır.",
      "Seçim sürecinde dikkat edilmesi gereken bir başka husus; tavsiye edilen avukatın gerçekten konuya hakim olup olmadığıdır. Yakınınıza birinin önermesi tek başına yeterli değildir; uzmanlık alanı uyuşmazlığınızla örtüşmüyorsa süreç beklediğinizden farklı şekilde ilerleyebilir.",
      "KARDAK Hukuk Bürosu olarak Ankara'da hukuki destek arayan bireylere ve şirketlere; sade bir iletişim, yazılı sözleşme ile şeffaf ücretlendirme, dosya başına ayrılmış zaman ve düzenli bilgi notu pratiği sunuyoruz. Ön görüşme her zaman ücretsizdir.",
    ],
  },
  {
    slug: "ankara-bosanma-cekismeli-rehber",
    title: "Ankara'da Çekişmeli Boşanma Davası: Yetkili Mahkeme, Süreç ve Stratejik Hatalar",
    excerpt:
      "Ankara Aile Mahkemelerinde çekişmeli boşanma davası açarken bilmeniz gereken yetki kuralları, boşanma sebepleri, delil disiplini, nafaka, velayet, tazminat ve sık yapılan stratejik hatalar.",
    category: "Aile Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-10",
    readMinutes: 10,
    body: [
      "Çekişmeli boşanma davası, eşlerin boşanmanın hukuki sonuçlarında anlaşamadıkları durumlarda Ankara Aile Mahkemelerinde açılan ve uzun soluklu bir yargılama süreciyle çözümlenen davadır. Süreç hem maddi hem de duygusal olarak yoğun bir hazırlık gerektirir.",
      "Yetkili mahkeme bakımından davacının yerleşim yeri ya da eşlerin son altı aydır birlikte oturdukları yer Aile Mahkemesi yetkilidir. Ankara'da yerleşim yeri olan ya da son altı aydır Ankara'da birlikte yaşayan eşler için Ankara Aile Mahkemeleri görevlidir. Aile mahkemesi bulunmayan ilçelerde asliye hukuk mahkemesi aile mahkemesi sıfatıyla davaya bakar.",
      "Boşanma sebepleri özel ve genel olmak üzere ikiye ayrılır. Özel sebepler arasında zina, hayata kast, onur kırıcı davranış, suç işleme, terk ve akıl hastalığı sayılırken; genel sebep evlilik birliğinin temelinden sarsılmasıdır. Hangi sebebin ileri sürüleceği, ispat yükünü ve sonucu doğrudan etkiler.",
      "Çekişmeli süreçte mahkeme; tanık beyanları, mesaj kayıtları, sosyal medya verileri, banka hareketleri, fotoğraf-video kayıtları ve uzman incelemelerini birlikte değerlendirir. Hukuka aykırı yollarla elde edilen delillerin yargılamada kabul edilmediği unutulmamalıdır.",
      "Velayet talebinde mahkeme öncelikle çocuğun üstün yararını gözetir. Yaş, eğitim ihtiyacı, anne-babanın çocukla kurduğu duygusal bağ ve pedagog raporları belirleyici unsurlardır. Velayet kararı kesinleşinceye kadar geçici velayet ve kişisel ilişki tedbirleri talep edilebilir.",
      "Tedbir nafakası dava süresince eşin ve çocukların geçinmesi için bağlanır. Karar kesinleştikten sonra ise iştirak nafakası çocuklar için, yoksulluk nafakası ise kusursuz veya az kusurlu eş için bağlanabilir. Yoksulluk nafakası süresiz olabilmektedir.",
      "Maddi tazminat, boşanma yüzünden mevcut veya beklenen menfaatleri zedelenen kusursuz veya daha az kusurlu eşe ödenir. Manevi tazminat ise kişilik haklarının saldırıya uğraması nedeniyle gündeme gelir ve genellikle aldatma, fiziksel şiddet gibi sebeplerle talep edilir.",
      "Edinilmiş mallara katılma rejimi 2002 sonrası evliliklerde yasal rejimdir. Boşanmayla birlikte tasfiyeye girer ve katılma alacağı ile değer artış payı talepleri ayrı bir mal rejimi davasında ele alınır. Bu dava, boşanma kararının kesinleşmesinden sonra açılabilir.",
      "Stratejik hatalar bakımından en sık görülenler; gereksiz tanık listesi vermek, hukuka aykırı delil sunmak, sosyal medyada karşı tarafa zarar verecek paylaşımlar yapmak ve ön görüşmede konuşulanları yazılı bir protokole bağlamadan adımlar atmaktır.",
      "Ankara'da çekişmeli boşanma davaları; delil toplama, tanık dinleme, bilirkişi raporu ve istinaf süreçleri nedeniyle ortalama 12-24 ay sürmektedir. Karmaşık mal rejimi içeren ya da yurt dışı boyutlu dosyalarda bu süre daha da uzayabilir.",
      "Çekişmeli süreci kısaltmanın en sağlıklı yolu; süreç içinde anlaşmalı boşanmaya geçiş kapısını açık tutmak ve bunun için iyi hazırlanmış bir protokol taslağı bulundurmaktır. Ankara Aile Mahkemelerinin çoğu, hâlâ uzlaşma sağlanabilen dosyaları takdirle değerlendirmektedir.",
      "KARDAK Hukuk Bürosu olarak Ankara'da çekişmeli boşanma davalarını; delil disiplini, müvekkil iletişimi ve mümkün olduğunda uzlaşma odaklı stratejilerle yönetiyor; her dosyada ölçülü ve sakin bir temsil sunuyoruz.",
    ],
  },
  {
    slug: "ankara-ceza-avukati-rehberi",
    title: "Ankara Ceza Avukatı: Soruşturma ve Kovuşturma Aşamasında Hak Arayışı",
    excerpt:
      "Ankara'da şüpheli ya da sanık sıfatıyla yer alınan ceza dosyalarında ifade, tutuklama, adli kontrol, kovuşturma, istinaf ve infaz aşamalarında bir Ankara ceza avukatının rolü ve kritik hakların pratik anlatımı.",
    category: "Ceza Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-08",
    readMinutes: 9,
    body: [
      "Ceza yargılaması; şüpheli, sanık veya mağdur sıfatıyla yer alınan en hassas hukuki süreçlerden biridir. Ankara'da ceza dosyaları soruşturma aşamasında Ankara Cumhuriyet Başsavcılığı tarafından, kovuşturma aşamasında ise Ankara Asliye veya Ağır Ceza Mahkemelerinde yürütülür.",
      "Soruşturma aşamasında ilk işlem genellikle ifade alınmasıdır. Şüphelinin susma hakkı, avukat bulundurma hakkı ve aleyhine delil göstermeme hakkı temel anayasal güvencelerdir. Ankara'da kollukta veya savcılıkta ifade verilirken bu hakların hatırlatılması zorunludur.",
      "İfade aşamasında avukat eşliğinde olmamak, çoğu zaman ileride telafisi güç hatalara yol açar. Hukukçu olmayan birinin teknik suç tipleri ve hukuki nitelendirmeler hakkında doğru beyanda bulunması beklenemez. Bu nedenle ilk anlardan itibaren bir Ankara ceza avukatıyla görüşmek önerilir.",
      "Tutuklama, Anayasa'nın 19. maddesi ve Ceza Muhakemesi Kanunu çerçevesinde ancak somut delillere ve kuvvetli suç şüphesine dayalı olarak verilebilen istisnai bir koruma tedbiridir. Ankara Sulh Ceza Hakimliklerinin tutuklama kararlarına karşı yedi gün içinde itiraz edilebilir.",
      "Adli kontrol, tutuklama yerine başvurulan ve yurt dışına çıkış yasağı, imza atma yükümlülüğü, ev hapsi gibi tedbirleri içerebilen bir kurumdur. Ankara'da uygulamada giderek artan biçimde adli kontrol tercih edilmekte; ancak ihlal hâlinde doğrudan tutuklamaya çevrilebilmektedir.",
      "Kovuşturma aşamasında iddianamenin kabulüyle birlikte dosya Ankara Asliye veya Ağır Ceza Mahkemesine devredilir. Hangi mahkemenin görevli olduğu, suça öngörülen ceza miktarına göre belirlenir. Ağırlaştırılmış müebbet, müebbet ve on yıldan fazla hapis cezalı suçlar Ağır Ceza Mahkemesinin görev alanındadır.",
      "Kovuşturma boyunca tanıkların dinlenmesi, sanığın savunma yapması, bilirkişi raporlarının değerlendirilmesi ve esas hakkındaki mütalaa süreçleri yer alır. Avukat; her aşamada delillere itiraz etme, ek delil sunma ve süre uzatma talep etme hakkını kullanır.",
      "Mağdur ve katılan vekilliği de ceza avukatlığının önemli bir parçasıdır. Mağdurun zararlarının tespit edilmesi, suçtan zarar gören sıfatıyla davaya katılma talebi ve maddi-manevi tazminat hakları stratejik biçimde takip edilir.",
      "Karar verildikten sonra istinaf yolu açıktır. Ankara Bölge Adliye Mahkemesi Ceza Daireleri istinaf incelemesi yapar; istinaf kararına karşı bazı dosyalarda Yargıtay'a temyiz yolu açıktır. Bu aşamalarda sürelerin titiz takibi büyük önem taşır.",
      "İnfaz süreci ise kararın kesinleşmesinden sonra başlar. Denetimli serbestlik, koşullu salıverilme, açık ceza infaz kurumuna ayrılma gibi pek çok kurum infaz hukukunun kapsamındadır. Hatalı infaz hesapları için Ankara İnfaz Hakimliklerine itiraz yolu açıktır.",
      "KARDAK Hukuk Bürosu olarak Ankara'da ceza dosyalarını; soruşturmanın ilk dakikasından infaza kadar her aşamada müvekkilin haklarını korumak temel anlayışıyla yürütüyor, ölçülü ve delile dayalı bir savunma diliyle çalışıyoruz.",
    ],
  },
  {
    slug: "anlasmali-bosanma-sureci",
    title: "Ankara'da Anlaşmalı Boşanma Süreci: Aile Mahkemesinde Adım Adım Rehber",
    excerpt:
      "Ankara Aile Mahkemelerinde anlaşmalı boşanma davası açmak için gerekli protokol, yetkili mahkeme, evraklar, ortalama süreler ve süreçte bir Ankara boşanma avukatının rolüne dair pratik bir rehber.",
    category: "Aile Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-06",
    readMinutes: 7,
    body: [
      "Anlaşmalı boşanma, Türk Medeni Kanunu'nun 166/3. maddesi kapsamında evliliğin en az bir yıl sürmesi şartıyla eşlerin tüm hukuki sonuçlarda anlaşması durumunda başvurulan ve Ankara Aile Mahkemelerinde nispeten kısa sürede tamamlanan bir süreçtir.",
      "Davanın açılabilmesi için eşlerden birinin yerleşim yerinin Ankara'da olması veya tarafların son altı aydır birlikte Ankara'da yaşamış olması yeterlidir. Aile mahkemesi bulunmayan ilçelerde asliye hukuk mahkemesi aile mahkemesi sıfatıyla davaya bakar.",
      "Anlaşmalı boşanma davasının üç temel aşaması vardır: ortak bir protokol hazırlanması, dava dilekçesinin yetkili Ankara Aile Mahkemesine sunulması ve hâkim huzurunda eşlerin protokoldeki iradelerini bizzat onaylaması.",
      "Protokol; mal paylaşımı, varsa müşterek çocuklar için velayet, kişisel ilişki günleri, iştirak ve yoksulluk nafakası, maddi-manevi tazminat ile diğer talepleri eksiksiz biçimde düzenlemelidir. Mahkeme, çocukların menfaatine aykırı gördüğü hükümlerde re'sen değişiklik talep edebilir.",
      "Dilekçeyle birlikte tarafların kimlik fotokopisi, evlilik cüzdanı sureti, varsa müşterek çocuklara ait nüfus kayıt örnekleri ve imzalı protokol mahkemeye sunulur. Eksik belgelerle açılan davalar usulden geri çevrilebilir ve süre kaybına yol açar.",
      "Ankara'da anlaşmalı boşanma davaları, mahkemelerin yoğunluğuna bağlı olarak çoğunlukla 4-8 hafta içinde tek celse ile sonuçlanır. Boşanma kararının kesinleşmesi için tebliğden itibaren iki haftalık istinaf süresinin geçmesi beklenir.",
      "Anlaşmalı sürecin en kritik noktası, protokolün ileride uyuşmazlık doğurmayacak biçimde net yazılmasıdır. Özellikle nafakanın yıllık artış oranı, kişisel ilişki günleri ve mal paylaşımına ilişkin ödeme takvimi gibi başlıklarda muğlak ifadeler ileride yeni davalara sebep olabilmektedir.",
      "Velayet kendisine bırakılmayan eş için belirlenen kişisel ilişki günleri; çocuğun yaşına, eğitim hayatına ve özel günlerine göre düzenlenmelidir. Yarıyıl, yaz tatili ve resmi bayramların kapsayıcı şekilde protokole yansıtılması ileride çıkabilecek tartışmaları engeller.",
      "Boşanmayla birlikte yasal mal rejimi olan edinilmiş mallara katılma rejimi tasfiye edilir. Anlaşmalı süreçte mal paylaşımı protokole net biçimde işlenebileceği gibi taraflar isterse mal rejimi tasfiyesini ayrı bir davaya bırakabilirler.",
      "Ankara Aile Mahkemelerinde anlaşmalı boşanmada yaşanan sık sorunlardan biri, tarafların protokolü duruşma günü değiştirmek istemesidir. Bu durumda mahkeme, anlaşmanın bozulduğunu kabul ederek davayı çekişmeliye dönüştürebilir.",
      "KARDAK Hukuk Bürosu olarak Ankara'da anlaşmalı boşanma süreçlerinde; protokolün dikkatle hazırlanması, eksik belgelerin önlenmesi ve duruşma sürecinin sade biçimde yönetilmesi için müvekkillerimize uçtan uca destek sağlıyoruz.",
    ],
  },
  {
    slug: "ankara-miras-davasi-veraset",
    title: "Ankara'da Miras Davası ve Veraset İlamı: Sulh Hukuk Mahkemesinde Adım Adım Süreç",
    excerpt:
      "Ankara Sulh Hukuk Mahkemelerinde veraset ilamı, mirasın reddi, terekenin tespiti, tenkis davası, muris muvazaası ve ortaklığın giderilmesi süreçlerini uygulama örnekleriyle anlatan kapsamlı bir Ankara miras avukatı rehberi.",
    category: "Miras Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-05-04",
    readMinutes: 9,
    body: [
      "Miras hukuku uyuşmazlıkları, mirasçılar arasında çoğu zaman duygusal ve mali gerginlikleri bir arada barındırır. Ankara'da miras davaları büyük ölçüde Sulh Hukuk ve Asliye Hukuk Mahkemelerinin görev alanındadır.",
      "Veraset ilamı çıkartmak miras süreçlerinin ilk adımıdır. Ankara'da veraset ilamı için Sulh Hukuk Mahkemelerine başvurulabileceği gibi, mirasçılar arasında uyuşmazlık yoksa noterler aracılığıyla da çıkartılabilmektedir. Yabancı uyruklu mirasçı bulunan dosyalarda yetki yalnızca mahkemelerdedir.",
      "Mirasın reddi başvurusunda süre üç aydır. Bu süre, mirasçının murisin ölümünü öğrendiği tarihten itibaren işlemeye başlar. Ankara Sulh Hukuk Mahkemesine yapılan başvuru sözlü veya yazılı olabilir. Sürenin geçirilmesi hâlinde miras kayıtsız şartsız kabul edilmiş sayılır.",
      "Terekenin tespiti, mirasın açıldığı an itibarıyla mal varlığının yargı önünde belgelenmesini sağlar. Sulh Hukuk Mahkemesinden istenebilen bu işlem; banka kayıtları, tapu, araç tescil, şirket pay defterleri ve menkul mallar üzerinden yürütülür.",
      "Tenkis davası, saklı paylı mirasçıların saklı paylarını ihlal eden bağışlamalar veya vasiyet hükümleri için açılır. Davanın açılabilmesi için saklı pay sahibinin saklı payına yapılan tecavüzü ve ölümü öğrenmesinden itibaren bir yıl, her hâlde mirasın açılmasından itibaren on yıllık süre içinde dava açılması gerekir.",
      "Muris muvazaası davası ise; murisin sağlığında, sırf saklı pay sahibi mirasçısını mirastan kaçırmak amacıyla taşınmaz devrettiği iddiasıyla gündeme gelir. Bu davalarda zamanaşımı yoktur ancak ispat yükü davacıdadır. Yargıtay'ın yerleşik içtihatları ışığında özellikle ekonomik karşılığı olmayan satışlar muvazaalı kabul edilmektedir.",
      "Ortaklığın giderilmesi (izale-i şuyu) davası, taşınmaz ve menkul mallarda ortak mülkiyetin sona erdirilmesi için açılır. Ankara'da Sulh Hukuk Mahkemelerinin görev alanındaki bu davalarda mahkeme; taşınmaz aynen taksim edilebiliyorsa aynen, edilemiyorsa satış suretiyle ortaklığı giderir.",
      "Vasiyetname düzenlemesi miras süreçlerinin önceden planlanmasında en etkili araçlardan biridir. Resmi vasiyetname noter huzurunda, el yazılı vasiyetname tarih ve imzayla murisin kendi el yazısıyla, sözlü vasiyet ise yalnızca olağanüstü koşullarda düzenlenebilir.",
      "Mirastan feragat sözleşmesi, muris sağlığında bir mirasçının ileride doğacak miras hakkından feragat etmesini sağlar. Bu sözleşme, noter huzurunda resmi şekilde yapılmadığı sürece geçerli değildir. Karşılıklı veya tek taraflı olarak düzenlenebilir.",
      "Ankara Sulh Hukuk Mahkemelerinde miras davalarının ortalama süresi; uyuşmazlığın niteliğine göre 8-18 ay arasında değişebilmektedir. Bilirkişi gerektiren karmaşık tereke incelemelerinde süre daha da uzayabilir.",
      "Pratik bir öneri olarak; mirasçılara muris öldükten sonra hızlıca veraset ilamı çıkarmak, banka ve tapu kayıtlarını dondurmak için tedbir talep etmek ve tereke borcu varsa mirasın reddi süresini kaçırmamak için ilk haftada bir Ankara miras avukatıyla görüşmek gerekir.",
      "KARDAK Hukuk Bürosu olarak Ankara'da miras dosyalarını; tereke tespiti, mirasın reddi, tenkis, muvazaa ve ortaklığın giderilmesi süreçlerinde mirasçıların menfaatlerini dengeli biçimde gözeterek yönetiyoruz.",
    ],
  },
  {
    slug: "ankara-ticaret-sirket-kurulumu",
    title: "Ankara'da Şirket Kuruluşu ve Ticari Sözleşme: Hukuki Süreç Rehberi",
    excerpt:
      "Ankara'da limited ya da anonim şirket kuruluşu, esas sözleşme hazırlığı, ticaret sicil tescili, ticari sözleşmeler, birleşme-devralma ve hissedarlar sözleşmesi süreçlerinde dikkat edilmesi gereken hukuki noktalar.",
    category: "Ticaret Hukuku",
    author: "Av. Servet Ağcakaya",
    date: "2026-05-02",
    readMinutes: 10,
    body: [
      "Ankara'da bir şirket kurmak ya da mevcut bir ticari ilişkiyi yazılı bir hukuki çerçeveye oturtmak; vergi, sosyal güvenlik, sözleşme ve sermaye hukukunu kapsayan disiplinler arası bir süreçtir.",
      "Şirket türünün belirlenmesi ilk ve en kritik adımdır. Türk Ticaret Kanunu kapsamındaki anonim şirket, limited şirket, kollektif ve komandit şirketler farklı sorumluluk rejimleri ve sermaye yükümlülükleri içerir. Ankara'da küçük ve orta ölçekli işletmeler için en yaygın tercih limited şirkettir.",
      "Limited şirkette ortaklar yalnızca koydukları sermaye payı ile sorumludur; ancak vergi ve sosyal güvenlik kamu alacaklarında müteselsil sorumluluk gündeme gelebilir. Anonim şirkette pay devri daha esnektir, ancak yönetim kurulu ve denetim yapısı daha kurumsal çalışma gerektirir.",
      "Esas sözleşmenin hazırlanması süreçte hukuki açıdan en belirleyici aşamadır. Şirketin amacı, sermaye yapısı, yönetim ve temsil yetkisi, kâr dağıtım esasları, pay devir kısıtlamaları ve genel kurul toplantı yöntemleri esas sözleşmede net düzenlenmelidir.",
      "Ankara Ticaret Sicili Müdürlüğüne tescil başvurusu, MERSİS üzerinden elektronik ortamda yapılır. Kuruluş başvurusunda ortakların imza beyannameleri, yerleşim yeri belgeleri, vergi numaraları ve esas sözleşme yer alır. Süreç ortalama 7-15 iş gününde tamamlanır.",
      "Şirket kuruluşundan sonra yapılması gereken işlemler; vergi dairesi açılış işlemleri, e-fatura ve e-defter mükellefiyeti, SGK işyeri tescili, Ankara Ticaret Odası kayıt işlemleri ve gerekli ise faaliyet ruhsatlarıdır.",
      "Ticari sözleşmeler kurumsal hayatta sıklıkla karşılaşılan ve yazılı düzenlenmediğinde ileride büyük ihtilaflara yol açabilen belgelerdir. Tedarik, distribütörlük, franchise, lisans, hizmet ve gizlilik sözleşmeleri Ankara'daki şirketlerin gündemindedir.",
      "İyi bir ticari sözleşmenin temel unsurları; tarafların net tanımı, edimlerin somut belirlenmesi, ödeme koşulları, gecikme faizi, fesih ve cezai şart hükümleri, mücbir sebep, gizlilik ve uyuşmazlık çözüm maddeleridir. Tahkim veya yetkili mahkeme şartı çoğu zaman ihmal edilmemelidir.",
      "Birleşme ve devralma süreçlerinde due diligence (hukuki inceleme), şirketin gerçek değerinin ortaya çıkarılması açısından kritiktir. Vergi, iş hukuku, sözleşme ve sermaye yapısı boyutlarında incelenmeyen şirketler ileride hedef alıcısı için ciddi sürprizler doğurabilir.",
      "Ortaklık uyuşmazlıkları, küçük şirketler için en yıpratıcı dosyalardan biridir. Ankara Asliye Ticaret Mahkemelerinde görülen bu davalarda pay devri, kâr dağıtımı ve yönetimden çıkarma süreçleri esas sözleşmedeki düzenlemeler ışığında değerlendirilir.",
      "Şirket ortakları için pratik bir öneri; ortaklık ilişkisinin başında hissedarlar sözleşmesi yapmak ve çıkış senaryolarını, pay devri kısıtlamalarını, drag-along ve tag-along haklarını yazılı belirlemektir. Sözleşmesiz başlayan ortaklıklar ileride ciddi hukuki maliyetlere yol açabilmektedir.",
      "KARDAK Hukuk Bürosu olarak Ankara'da şirket kuruluşu, esas sözleşme tasarımı, ticari sözleşmeler ve birleşme-devralma süreçlerinde KOBİ'lerden ölçekli şirketlere kadar geniş bir yelpazeye uzun soluklu hukuki destek sunuyoruz.",
    ],
  },
  {
    slug: "ankara-gayrimenkul-tapu-iptal",
    title: "Ankara'da Tapu İptal ve Tescil Davası: Gayrimenkul Uyuşmazlıklarında Yol Haritası",
    excerpt:
      "Ankara'da tapu iptal ve tescil davası açılırken yetkili Asliye Hukuk Mahkemesi, muris muvazaası, hile, ehliyetsizlik gibi sık görülen hukuki sebepler, kat mülkiyeti ve imar uyuşmazlıkları üzerine kapsamlı rehber.",
    category: "Gayrimenkul Hukuku",
    author: "Av. Servet Ağcakaya",
    date: "2026-04-28",
    readMinutes: 8,
    body: [
      "Tapu iptal ve tescil davası, Türk hukukunda gayrimenkul mülkiyetiyle ilgili uyuşmazlıkların en sık karşılaşılan dava türlerinden biridir. Ankara'da bu davalar, taşınmazın bulunduğu yerdeki Asliye Hukuk Mahkemesinin görev alanındadır.",
      "Davanın açılmasında en sık görülen sebepler; muris muvazaası, satış sözleşmesinin geçersizliği, hile, ehliyetsizlik, hukuken geçerli olmayan irade beyanı ve imar yolsuzluğudur. Her sebep farklı ispat unsurları gerektirir.",
      "Muris muvazaası davası, miras hukukuyla iç içe geçen ve Ankara Asliye Hukuk Mahkemelerinde sık görülen bir dava türüdür. Murisin sağlığında saklı pay sahibi mirasçısını mirastan kaçırmak amacıyla taşınmazı görünüşte sattığı kabul edilen işlemler bu davaya konu olmaktadır.",
      "Ehliyetsizlik nedeniyle açılan tapu iptal davalarında, taşınmazın devri sırasında devredenin akıl sağlığı yerinde olmaması veya işin niteliği ve sonuçlarını kavrayacak durumda olmaması gerekir. Mahkeme; sağlık kuruluşu raporları, tanık beyanları ve adli tıp incelemesiyle değerlendirme yapar.",
      "Hile sebebiyle açılan davalarda ise satıcının ya da alıcının diğer tarafı yanıltıcı beyanlarla iradeyi etkilediği kabul edilir. İspat yükü hile iddiasında bulunan tarafa aittir ve genellikle yazılı belgeler, mesaj kayıtları ve tanık beyanları üzerinden değerlendirme yapılır.",
      "Kira ilişkisinden doğan tahliye davaları gayrimenkul hukukunun bir başka yoğun alanıdır. Ankara'da konut ve çatılı işyeri kiralarında tahliye davaları Sulh Hukuk Mahkemelerinin görev alanındadır; özel sebepler dışında en az on yıllık kira ilişkisinde özel ihbar yolu öngörülmüştür.",
      "Kat mülkiyeti uyuşmazlıkları ise apartman ve site yönetiminden doğan anlaşmazlıkları kapsar. Ortak gider alacakları, genel kurul kararlarının iptali, yönetici tayini ve ortak yer kullanımı süreçleri Ankara Sulh Hukuk Mahkemelerinde sık karşılaşılan dava türlerindendir.",
      "Gayrimenkul alım-satım sözleşmelerinde tapu siciline güven ilkesi büyük önem taşır. Tapuya tescil edilmiş bir mülkiyet kaydına iyi niyetle güvenen üçüncü kişi, sonradan iptal davasıyla karşılaştığında kazanmış olduğu hakkı koruyabilir. Bu nedenle alımdan önce tapu kayıt geçmişi titizlikle incelenmelidir.",
      "İmar uygulamalarından doğan ihtilaflar ise idari yargının görev alanındadır. Ankara'da imar planı değişiklikleri, parselasyon işlemleri ve kamulaştırma kararlarına karşı Ankara İdare Mahkemelerine başvurulur. Sürelerin titiz takibi şarttır; iptal davası süresi tebliğden itibaren altmış gündür.",
      "Pratik bir öneri olarak; Ankara'da gayrimenkul almadan önce tapu sorgusu, imar durumu sorgulaması, varsa şerh ve haciz kayıtlarının incelenmesi, kat mülkiyeti durumunun değerlendirilmesi ve yapı kullanma izninin var olduğunun teyit edilmesi sonradan açılacak davaların büyük çoğunluğunu önler.",
      "Yargılama süreleri açısından, tapu iptal davaları Ankara'da bilirkişi gerektirmesi nedeniyle ortalama 14-22 ay sürmektedir. İstinaf ve Yargıtay aşamalarıyla birlikte toplam süre üç yılı bulabilmektedir.",
      "KARDAK Hukuk Bürosu olarak Ankara'da gayrimenkul davalarını; alım öncesi due diligence çalışmasından tapu iptal, tahliye, kat mülkiyeti ve imar süreçlerine kadar her aşamada müvekkillerimizle birlikte yürütüyoruz.",
    ],
  },
  {
    slug: "ise-iade-davasi-sartlari",
    title: "İşe İade Davası Şartları ve Süreleri: Ankara İş Mahkemesi Uygulaması",
    excerpt:
      "Ankara'da haksız feshe maruz kalan işçinin işe iade davası açabilmesi için gerekli şartlar, arabuluculuk zorunluluğu, dava süresi, karar sonrası işverenin yükümlülükleri ve sık yapılan hatalar.",
    category: "İş Hukuku",
    author: "Av. Berk Erdem Işık",
    date: "2026-04-22",
    readMinutes: 8,
    body: [
      "İşe iade davası, iş güvencesi kapsamında çalışan işçinin iş sözleşmesinin işveren tarafından geçerli bir sebebe dayanmadan feshedilmesi hâlinde başvurabileceği ve Ankara İş Mahkemelerinin bakmakla görevli olduğu önemli bir hukuki yoldur.",
      "Davanın açılabilmesi için öncelikle iş güvencesi şartlarının sağlanması gerekir. İşçinin çalıştığı işyerinde en az otuz işçinin bulunması, işçinin en az altı aylık kıdeminin olması ve iş sözleşmesinin işveren tarafından feshedilmiş olması temel şartlardır. Belirli süreli iş sözleşmeleri ve işveren vekili sıfatıyla çalışanlar bazı durumlarda iş güvencesi kapsamında değildir.",
      "Fesih bildiriminin işçiye tebliğinden itibaren bir aylık süre içinde işçinin arabulucuya başvurması zorunludur. Ankara'da Çalışma ve İş Kurumu İl Müdürlüğüne bağlı arabulucu listelerinden seçim yapılabileceği gibi taraflar ortak bir arabulucu üzerinde de anlaşabilir.",
      "Arabuluculuk görüşmelerinde anlaşma sağlanırsa süreç burada sona erer ve anlaşma tutanağı ilam niteliğinde icra kabiliyetine sahip olur. Anlaşma sağlanamazsa son tutanağın düzenlenmesinden itibaren iki hafta içinde Ankara İş Mahkemesinde dava açılmalıdır.",
      "Hak düşürücü nitelikteki bu süreler kaçırıldığında dava esastan değil; süre yönünden reddedilir. Bu nedenle fesih bildirimi tebliğ alındığı anda takvim oluşturmak ve bir Ankara iş avukatıyla görüşmek kritik önem taşır.",
      "Mahkeme, feshin geçerli sebebe dayanıp dayanmadığını araştırırken işyeri kayıtları, performans değerlendirme raporları, disiplin kurulu kararları, tanık beyanları ve gerektiğinde bilirkişi incelemesinden yararlanır. Ankara İş Mahkemelerinin uygulamasında savunma alınmadan yapılan fesihler büyük ölçüde geçersiz kabul edilmektedir.",
      "İşe iade kararı kesinleştiğinde işçi, kararın kendisine tebliğinden itibaren on iş günü içinde işverene başvurarak işe başlamak istediğini bildirir. İşveren bu başvurudan itibaren bir ay içinde işçiyi işe başlatmakla yükümlüdür.",
      "İşveren işçiyi tekrar işe başlatmazsa, mahkemece belirlenen 4 ile 8 aylık ücret tutarındaki işe başlatmama tazminatı ile boşta geçen sürenin en çok dört aylık ücret tutarı işçiye ödenmek zorundadır. Bu hakların talep edilebilmesi için işçinin süresi içinde işverene başvurmuş olması şarttır.",
      "İşe iade davası ile birlikte ödenmemiş kıdem ve ihbar tazminatı, fazla mesai, hafta tatili ve genel tatil ücreti gibi işçilik alacakları ayrı bir davayla veya birleştirilerek talep edilebilir. Ankara'da bu davalar çoğunlukla aynı iş mahkemesinde görülür.",
      "İşveren tarafının dikkat etmesi gereken nokta ise fesih sürecini yazılı belgelerle desteklemek, savunma almayı ihmal etmemek ve performans uyarılarını dosyaya işlemektir. Aksi hâlde feshin geçersizliği yüksek olasılıktır.",
      "KARDAK Hukuk Bürosu olarak Ankara İş Mahkemelerinde işe iade davalarını; sürelerin titiz takibi, delil hazırlığı ve müvekkilin işletmeyle ilişkisinin korunması ekseninde stratejik biçimde yönetiyoruz.",
    ],
  },
  {
    slug: "ankara-icra-takibi-rehberi",
    title: "Ankara'da İcra Takibi ve Alacak Tahsili: Avukat Eşliğinde Süreç",
    excerpt:
      "Ankara İcra Müdürlüklerinde ilamlı ve ilamsız takip, itirazın kaldırılması, haciz, maaş haczi, satış, menfi tespit ve istihkak davaları üzerinden alacak tahsili sürecinin pratik anlatımı.",
    category: "İcra Hukuku",
    author: "Av. Berk Erdem Işık",
    date: "2026-04-18",
    readMinutes: 8,
    body: [
      "İcra ve iflas hukuku, alacaklının alacağını devlet eliyle tahsil etmek için başvurduğu pratik ama teknik bir hukuk alanıdır. Ankara'da icra takipleri Ankara Adliyesindeki çok sayıda İcra Müdürlüğü ve İcra Hukuk Mahkemesi marifetiyle yürütülür.",
      "Takipler temelde iki başlıkta toplanır: ilamsız takip ve ilamlı takip. İlamsız takipte mahkeme kararı olmadan, doğrudan alacak iddiasıyla takip başlatılır. İlamlı takipte ise alacaklı, elinde mahkeme ilamı ya da ilam niteliğinde belgeyle takibe geçer.",
      "İlamsız takipte borçluya ödeme emri tebliğ edilir ve borçlu yedi gün içinde itiraz edebilir. İtiraz takibi otomatik olarak durdurur. Bu noktadan sonra alacaklının itirazın kaldırılması veya itirazın iptali davası açması gerekir.",
      "İtirazın kaldırılması davası Ankara İcra Hukuk Mahkemesinde, itirazın iptali davası ise genel mahkemelerde açılır. Hangi davanın açılacağı, alacaklının elindeki belgelerin niteliğine göre belirlenir; imzasız belge varsa itirazın iptali yolu zorunlu hâle gelmektedir.",
      "İlamlı takipte ise borçlu, ödeme emrinin tebliğinden itibaren yedi gün içinde itiraz edebilir; ancak bu itiraz takibi otomatik durdurmaz. İcra hâkiminden ayrıca takibin durdurulması talep edilmelidir.",
      "Haciz aşaması, takibin kesinleşmesinden sonra başlar. Alacaklının haciz talebi üzerine İcra Müdürlüğü; borçlunun mal varlığı, banka hesapları, maaşı, taşınmazları, araçları ve üçüncü kişilerdeki alacakları üzerine haciz koyabilir. Ankara'da banka haciz işlemleri büyük ölçüde elektronik sistemler üzerinden yürütülmektedir.",
      "Maaş haczinde, borçlunun maaşının dörtte birinin haczedilmesi kuraldır. Asgari geçim tutarı altında kalan maaşlar haczedilemez. Birden fazla haciz varsa sıraya alınır ve önceki haczin tahsilinden sonra sıradakine geçilir.",
      "Satış aşaması, haczedilen malların paraya çevrilmesi sürecidir. Taşınmazlarda satış genellikle elektronik ihale yoluyla yapılır. İhale şartlarının sağlanmaması, kıymet takdirine itiraz veya satış ilanındaki eksiklikler ihalenin feshine yol açabilir.",
      "Menfi tespit davası, borçlu olduğu iddia edilen kişinin aslında borçlu olmadığını mahkeme önünde kanıtlamak amacıyla açtığı davadır. Takip başlamadan veya başladıktan sonra açılabilir; takipten sonra açıldığında ihtiyati tedbir kararıyla takip durdurulabilir.",
      "İstihkak davası ise haczedilen malın üçüncü kişiye ait olduğu iddiasıyla açılır. Borçlunun yanında oturan akrabaların eşyalarının hatalı haczedilmesi gibi durumlarda gündeme gelir ve Ankara İcra Hukuk Mahkemesinin görev alanındadır.",
      "Konkordato süreçleri, borca batık durumdaki şirketlerin iflasını öteleyerek borçlarını yeniden yapılandırmasına olanak sağlar. Konkordato başvurusu Ankara Asliye Ticaret Mahkemesine yapılır ve geçici mühlet, kesin mühlet ve komiser atanması gibi aşamalardan oluşur.",
      "Pratik öneri olarak; alacaklıların icra takibi başlatmadan önce ihtarname göndererek müzakere zemini araması, borçluların ise tebliğ aldıkları her ödeme emrini titizlikle takip ederek itiraz süresini kaçırmaması esastır. Yedi günlük itiraz süresi tüm sürecin seyrini belirler.",
      "KARDAK Hukuk Bürosu olarak Ankara'da icra takiplerini, itirazın kaldırılması, menfi tespit, istihkak, ihalenin feshi ve konkordato dosyalarını; hızlı işlem disipliniyle ve müvekkilin ticari ilişkilerini koruyacak biçimde yönetiyoruz.",
    ],
  },
  {
    slug: "kira-uyarlama-davasi",
    title: "Kira Uyarlama Davası: Ankara'da Hangi Durumlarda ve Hangi Mahkemede Açılır?",
    excerpt:
      "Ankara'da kira sözleşmelerinde aşırı ifa güçlüğü doğduğunda kira uyarlama davası nasıl açılır, hangi Sulh Hukuk Mahkemesi yetkilidir, bilirkişi süreci ve ortalama süreler nasıl ilerler?",
    category: "Gayrimenkul Hukuku",
    author: "Av. Servet Ağcakaya",
    date: "2026-03-30",
    readMinutes: 7,
    body: [
      "Kira uyarlama davası, Türk Borçlar Kanunu'nun 138. maddesinde düzenlenen ve aşırı ifa güçlüğü ortaya çıktığında kira bedelinin yeniden belirlenmesini sağlayan bir dava türüdür. Ankara'da bu davalar görevli Sulh Hukuk Mahkemelerinde açılır.",
      "Davanın açılabilmesi için sözleşmenin kurulduğu anda taraflarca öngörülemeyen olağanüstü bir durumun ortaya çıkmış olması, bu durumun borçludan kaynaklanmamış olması, mevcut şartlar altında ifanın borçludan beklenemeyecek hâle gelmiş olması ve borçlunun edimini henüz ifa etmemiş olması ya da ifa güçlüğünü saklı tutarak ifa etmiş olması gerekir.",
      "Yetkili mahkeme bakımından, kira ilişkisinin kurulduğu taşınmazın bulunduğu yer Sulh Hukuk Mahkemesi kural olarak yetkilidir. Ankara'daki bir taşınmaz için kira uyarlama davası Ankara Sulh Hukuk Mahkemelerinde görülür.",
      "Uygulamada en sık karşılaşılan kira uyarlama davaları; yüksek enflasyon, döviz kurundaki ani değişimler ve ekonomik kriz dönemlerinde gündeme gelmektedir. Mahkemeler, talebin değerlendirilmesinde piyasa kira rayicini, sözleşmedeki artış mekanizmasını ve ekonomik koşullardaki değişimi birlikte ele alır.",
      "Yargıtay'ın yerleşik içtihatları; en az beş yıl ve daha uzun süreli kira ilişkilerinde uyarlama talebinin daha kabul edilebilir olduğunu göstermektedir. Daha kısa süreli sözleşmelerde mahkemeler genellikle yıllık artış hükümlerinin dengeyi koruduğunu kabul etmektedir.",
      "Davayı açmadan önce kiraya verene yazılı bildirimde bulunmak ve müzakere zemini aramak hem hukuki sürecin sağlığı hem de delil oluşturma açısından önerilir. Noter aracılığıyla yapılan ihtarname, mahkeme aşamasında iyi niyetli yaklaşımın somut göstergesi olarak değerlendirilmektedir.",
      "Bilirkişi raporu, kira uyarlama davalarının en kritik unsurlarından biridir. Mahkeme; piyasa rayici, taşınmazın konumu, niteliği, yapı kalitesi ve benzer taşınmazların kira değerlerini içeren rapora dayanarak uyarlama oranını belirler.",
      "Ankara'da kira uyarlama davaları, mahkemelerin iş yoğunluğu ve bilirkişi raporlarının teslim süresine bağlı olarak ortalama 8-14 ay sürmektedir. İstinaf sürecinin de eklenmesi durumunda toplam süre 18 ayı aşabilmektedir.",
      "Önemli bir husus; kira uyarlama davası kira sözleşmesini sona erdirmez. Yalnızca kira bedelini yeniden belirler. Tahliye gibi sonuçlar isteniyorsa ayrı bir tahliye davası açılması gerekir.",
      "Kiraya veren açısından önemli ipucu, sözleşmeyi düzenlerken artış hükmünü Türk Borçlar Kanunu'nun 344. maddesine uygun ve tüketici endeksine endeksli biçimde belirlemektir. Bu şekilde olağan koşullarda artış otomatik olarak gerçekleşir ve uyarlama davasına gerek kalmaz.",
      "KARDAK Hukuk Bürosu olarak Ankara'da kira uyarlama ve tahliye davalarını; sözleşme analizinden bilirkişi sürecine kadar her aşamada müvekkillerimizle birlikte yürütüyor, mümkün olduğunda öncelikle müzakere zemini kuruyoruz.",
    ],
  },
  {
    slug: "miras-paylasimi-temel-kavramlar",
    title: "Miras Paylaşımında Temel Kavramlar ve Ankara'da Süreç",
    excerpt:
      "Tenkis, mirasın reddi, muris muvazaası, saklı pay, veraset ilamı… Ankara'da miras paylaşımı süreçlerinde mirasçıların bilmesi gereken temel kavramlar ve kritik süreler.",
    category: "Miras Hukuku",
    author: "Av. Mahmut KARDAK",
    date: "2026-03-15",
    readMinutes: 9,
    body: [
      "Miras hukuku, kişinin ölümü ile birlikte mal varlığının kimlere ne şekilde geçeceğini düzenleyen hassas bir uygulama alanıdır. Türk Medeni Kanunu'nun 495 ve devamındaki maddelerinde mirasçılar, saklı pay sahipleri ve miras paylaşımının esasları düzenlenmiştir.",
      "Veraset ilamı, mirasçıların murisin terekesi üzerinde hak sahibi olduğunu gösteren resmi belgedir. Ankara'da veraset ilamı için Sulh Hukuk Mahkemelerine başvurulabileceği gibi, basit durumlarda noterler aracılığıyla da çıkartılabilmektedir.",
      "Saklı pay, kanun tarafından korunan asgari miras hakkıdır. Altsoy, eş ve anne-baba kanunda sayılan saklı pay sahipleridir. Murisin yaptığı bağışlamalar ya da vasiyetname düzenlemeleri saklı payı ihlal ediyorsa, ihlale uğrayan mirasçı tenkis davası açabilir.",
      "Mirasın reddi, mirasçının terekenin borca batık olması veya kendi tercihiyle mirasçılıktan çekilmek istemesi hâllerinde başvurduğu yoldur. Reddin geçerli olabilmesi için murisin ölümünün öğrenildiği tarihten itibaren üç ay içinde mirasçının yerleşim yerindeki Sulh Hukuk Mahkemesine yazılı veya sözlü olarak bildirilmesi gerekir.",
      "Ankara'da mirasın reddi başvuruları genellikle Ankara Sulh Hukuk Mahkemelerine yapılır. Sürenin geçirilmesi hâlinde miras kayıtsız şartsız kabul edilmiş sayılır ve mirasçı murisin tüm borçlarından kişisel mal varlığıyla sorumlu hâle gelir.",
      "Terekenin tespiti davası, mirasçıların murisin ölümü anındaki mal varlığını mahkeme önünde belgelemek için açtığı bir davadır. Bu dava, ileride açılacak ortaklığın giderilmesi davalarında çok değerli bir delil zemini oluşturur.",
      "Ortaklığın giderilmesi davası (izale-i şuyu), mirasçılar arasında ortak mülkiyetin sona erdirilmesi için açılır. Ankara'da bu davalar Sulh Hukuk Mahkemelerinin görev alanında olup taşınmaz mallarda satış suretiyle ortaklığın giderilmesi en sık görülen yöntemdir.",
      "Murisin sağlığında yaptığı bağışlamaların büyük bir kısmının mirastan kaçırma amacıyla yapıldığı iddia ediliyorsa muris muvazaası davası açılabilir. Yargıtay'ın yerleşik içtihatları; özellikle sırf saklı pay sahibi mirasçıyı mirastan mahrum bırakma kastıyla yapılan satışları muvazaalı kabul etmektedir.",
      "Vasiyetname düzenlenmesi, miras paylaşımında ileride çıkacak uyuşmazlıkları büyük ölçüde önler. Resmi vasiyetname noter huzurunda düzenlenir; el yazılı vasiyetnamede tarih, imza ve içerik tamamen muris tarafından yazılmalıdır. Sözlü vasiyetname ise yalnızca olağanüstü koşullarda geçerlidir.",
      "Sürelerin titiz takibi miras süreçlerinin en kritik noktasıdır. Mirasın reddi için üç ay, tenkis davası için on yıllık zamanaşımı, muris muvazaası davasında zamanaşımı sınırlaması bulunmaması gibi sürelerin doğru değerlendirilmesi avukatın temel görevidir.",
      "KARDAK Hukuk Bürosu olarak Ankara'da miras davalarını; tereke tespiti, veraset ilamı, mirasın reddi, tenkis ve ortaklığın giderilmesi süreçlerinde uçtan uca yönetiyor; gerektiğinde tarafları arabuluculuk yoluyla anlaşmaya yönlendirebiliyoruz.",
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}
